/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerEnvBindings` (hash: 79c049bece6f6d75d350b3718fa9413f)
interface __BaseEnv_WorkerEnvBindings {
	CACHE_FRESH_TTL_SECONDS: "600";
	CACHE_STALE_TTL_SECONDS: "3600";
	CACHE_FAILURE_COOLDOWN_SECONDS: "30";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_WorkerEnvBindings {}
}
interface WorkerEnvBindings extends __BaseEnv_WorkerEnvBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CACHE_FRESH_TTL_SECONDS" | "CACHE_STALE_TTL_SECONDS" | "CACHE_FAILURE_COOLDOWN_SECONDS">> {}
}
